root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && go build -o sling ."
  bin = "./sling serve"
  include_ext = ["go", "templ", "yaml"]
  exclude_regex = [ "_test.go", "_templ.go"]

[log]
  time = true

[proxy]
  enabled = true
  proxy_port = 3001
  app_port = 8080 
