// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><title>Sling Board</title><script src=\"https://unpkg.com/htmx.org@2.0.4\" crossorigin=\"anonymous\"></script><script src=\"https://unpkg.com/htmx-ext-ws@2.0.2\" crossorigin=\"anonymous\"></script><style>\n        .sling-message {\n          padding: 10px;\n          border-bottom: 1px solid #ddd;\n        }\n      </style></head><body><h1>Sling Board</h1><div id=\"slings\" hx-ext=\"ws\" ws-connect=\"/slings\" ws-receive></div><script>\n      document.addEventListener(\"htmx:wsMessage\", function(evt) {\n        console.log(\"HTMX WebSocket Message Received:\", evt.detail.message);\n      });\n\n        document.addEventListener(\"htmx:wsMessage\", function(evt) {\n            let slings = document.getElementById(\"slings\");\n            if (!slings) return;\n\n            // Ensure the message is properly extracted\n            let message = evt.detail.message; \n\n            // Safely insert the new message\n            slings.insertAdjacentHTML(\"beforeend\", message);  \n\n            // Auto-scroll to the latest message\n            slings.scrollTop = slings.scrollHeight; \n        });\n        document.addEventListener(\"htmx:wsMessage\", function(evt) {\n    console.log(\"Received WS Message:\", evt.detail.message);\n});\n\n    </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
